language: go

go:
- 1.10.x
- tip

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libraptor2-dev libmagic-dev
- go get -u github.com/golang/dep/...
- dep ensure

script:
- ./make test